-- =============================================
-- GAMES FEATURE: Database Schema
-- =============================================
-- This migration adds tables for the couples games system
-- including categories, game types, prompts, sessions, and responses.

-- =============================================
-- 1. GAME CATEGORIES
-- Parent categories for organizing games
-- =============================================
CREATE TABLE IF NOT EXISTS game_categories (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    name text NOT NULL,           -- e.g., "Discovery", "As a Couple", "Date Night", "Little Spice"
    description text,
    icon_name text,               -- Lucide icon name
    gradient_colors text[],       -- e.g., ARRAY['#E53935', '#C62828']
    sort_order int DEFAULT 0,
    is_adult boolean DEFAULT false,
    created_at timestamptz DEFAULT now()
);

-- =============================================
-- 2. GAME TYPES
-- Subcategories/game modes within each category
-- =============================================
CREATE TABLE IF NOT EXISTS game_types (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    category_id uuid REFERENCES game_categories(id) ON DELETE CASCADE,
    name text NOT NULL,           -- e.g., "Crush", "Deep Night", "Would You Rather Hot"
    slug text UNIQUE NOT NULL,    -- e.g., "would-you-rather-hot" for routing
    description text,
    icon_name text,
    gradient_colors text[],
    is_adult boolean DEFAULT false,
    has_virtual_mode boolean DEFAULT false,   -- For Little Spice games
    has_spice_meter boolean DEFAULT false,    -- Enable spice meter for this game
    gameplay_type text NOT NULL DEFAULT 'prompt', -- e.g., "prompt", "choice", "dare", "vote", "quiz"
    sort_order int DEFAULT 0,
    created_at timestamptz DEFAULT now()
);

-- =============================================
-- 3. GAME PROMPTS (Global Seed Pool)
-- Fallback prompts when AI is unavailable
-- =============================================
CREATE TABLE IF NOT EXISTS game_prompts (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    game_type_id uuid REFERENCES game_types(id) ON DELETE CASCADE,
    prompt_text text NOT NULL,
    option_a text,                -- For "Would You Rather" style games
    option_b text,                -- For "Would You Rather" style games
    mode text DEFAULT 'both' CHECK (mode IN ('in_person', 'virtual', 'both')),
    heat_level int DEFAULT 1 CHECK (heat_level BETWEEN 1 AND 4), -- 1=mild, 2=warm, 3=hot, 4=inferno
    is_seed boolean DEFAULT true, -- True for manually seeded, false for AI-generated
    created_at timestamptz DEFAULT now()
);

-- =============================================
-- 4. BOND GAME PROMPTS (AI-Generated Cache)
-- Prompts generated by AI and cached per bond
-- =============================================
CREATE TABLE IF NOT EXISTS bond_game_prompts (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    bond_id uuid REFERENCES bonds(id) ON DELETE CASCADE,
    game_type_id uuid REFERENCES game_types(id) ON DELETE CASCADE,
    prompt_text text NOT NULL,
    option_a text,
    option_b text,
    mode text DEFAULT 'both' CHECK (mode IN ('in_person', 'virtual', 'both')),
    heat_level int DEFAULT 2 CHECK (heat_level BETWEEN 1 AND 4),
    is_used boolean DEFAULT false,  -- Track if prompt has been shown
    created_at timestamptz DEFAULT now(),
    
    -- Prevent duplicate prompts per bond per game type
    UNIQUE(bond_id, game_type_id, prompt_text)
);

-- =============================================
-- 5. GAME SESSIONS (Real-time)
-- Active game sessions between partners
-- =============================================
CREATE TABLE IF NOT EXISTS game_sessions (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    bond_id uuid REFERENCES bonds(id) ON DELETE CASCADE,
    game_type_id uuid REFERENCES game_types(id) ON DELETE CASCADE,
    mode text DEFAULT 'in_person' CHECK (mode IN ('in_person', 'virtual')),
    heat_level int DEFAULT 2 CHECK (heat_level BETWEEN 1 AND 4),
    current_prompt_index int DEFAULT 0,
    prompts jsonb NOT NULL DEFAULT '[]',  -- Array of prompt IDs for this session
    user_1_ready boolean DEFAULT false,   -- For sync mechanics
    user_2_ready boolean DEFAULT false,
    user_1_response text,                 -- Current prompt response from user 1
    user_2_response text,                 -- Current prompt response from user 2
    started_at timestamptz DEFAULT now(),
    ended_at timestamptz,
    is_active boolean DEFAULT true,
    created_at timestamptz DEFAULT now()
);

-- Index for finding active sessions
CREATE INDEX IF NOT EXISTS idx_game_sessions_active ON game_sessions(bond_id, game_type_id) WHERE is_active = true;

-- =============================================
-- 6. GAME RESPONSES (History)
-- Track all user choices/answers for stats
-- =============================================
CREATE TABLE IF NOT EXISTS game_responses (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    session_id uuid REFERENCES game_sessions(id) ON DELETE CASCADE,
    prompt_id uuid,               -- Reference to prompt (could be from either prompts table)
    prompt_source text DEFAULT 'bond' CHECK (prompt_source IN ('seed', 'bond')),
    user_id uuid REFERENCES profiles(id) ON DELETE CASCADE,
    response text,                -- 'A', 'B', or free text
    created_at timestamptz DEFAULT now()
);

-- =============================================
-- 7. ROW LEVEL SECURITY (RLS)
-- =============================================

-- Enable RLS on all new tables
ALTER TABLE game_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE game_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE game_prompts ENABLE ROW LEVEL SECURITY;
ALTER TABLE bond_game_prompts ENABLE ROW LEVEL SECURITY;
ALTER TABLE game_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE game_responses ENABLE ROW LEVEL SECURITY;

-- Categories and Types are public read (game catalog)
CREATE POLICY "Anyone can view game categories" ON game_categories
    FOR SELECT USING (true);

CREATE POLICY "Anyone can view game types" ON game_types
    FOR SELECT USING (true);

-- Global prompts are readable by anyone (fallback)
CREATE POLICY "Anyone can view seed prompts" ON game_prompts
    FOR SELECT USING (is_seed = true);

-- Bond-specific prompts: only bond members can view/manage
CREATE POLICY "Bond members can view their prompts" ON bond_game_prompts
    FOR SELECT USING (
        auth.uid() IN (
            SELECT user_1_id FROM bonds WHERE id = bond_id
            UNION
            SELECT user_2_id FROM bonds WHERE id = bond_id
        )
    );

CREATE POLICY "Bond members can insert prompts" ON bond_game_prompts
    FOR INSERT WITH CHECK (
        auth.uid() IN (
            SELECT user_1_id FROM bonds WHERE id = bond_id
            UNION
            SELECT user_2_id FROM bonds WHERE id = bond_id
        )
    );

CREATE POLICY "Bond members can update prompts" ON bond_game_prompts
    FOR UPDATE USING (
        auth.uid() IN (
            SELECT user_1_id FROM bonds WHERE id = bond_id
            UNION
            SELECT user_2_id FROM bonds WHERE id = bond_id
        )
    );

-- Game sessions: only bond members can view/manage
CREATE POLICY "Bond members can view sessions" ON game_sessions
    FOR SELECT USING (
        auth.uid() IN (
            SELECT user_1_id FROM bonds WHERE id = bond_id
            UNION
            SELECT user_2_id FROM bonds WHERE id = bond_id
        )
    );

CREATE POLICY "Bond members can create sessions" ON game_sessions
    FOR INSERT WITH CHECK (
        auth.uid() IN (
            SELECT user_1_id FROM bonds WHERE id = bond_id
            UNION
            SELECT user_2_id FROM bonds WHERE id = bond_id
        )
    );

CREATE POLICY "Bond members can update sessions" ON game_sessions
    FOR UPDATE USING (
        auth.uid() IN (
            SELECT user_1_id FROM bonds WHERE id = bond_id
            UNION
            SELECT user_2_id FROM bonds WHERE id = bond_id
        )
    );

CREATE POLICY "Bond members can delete sessions" ON game_sessions
    FOR DELETE USING (
        auth.uid() IN (
            SELECT user_1_id FROM bonds WHERE id = bond_id
            UNION
            SELECT user_2_id FROM bonds WHERE id = bond_id
        )
    );

-- Game responses: only session participants can view/manage
CREATE POLICY "Session participants can view responses" ON game_responses
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM game_sessions gs
            JOIN bonds b ON gs.bond_id = b.id
            WHERE gs.id = session_id
            AND auth.uid() IN (b.user_1_id, b.user_2_id)
        )
    );

CREATE POLICY "Session participants can insert responses" ON game_responses
    FOR INSERT WITH CHECK (
        auth.uid() = user_id AND
        EXISTS (
            SELECT 1 FROM game_sessions gs
            JOIN bonds b ON gs.bond_id = b.id
            WHERE gs.id = session_id
            AND auth.uid() IN (b.user_1_id, b.user_2_id)
        )
    );

-- =============================================
-- 8. REALTIME SUBSCRIPTIONS
-- =============================================
ALTER PUBLICATION supabase_realtime ADD TABLE game_sessions;
ALTER PUBLICATION supabase_realtime ADD TABLE game_responses;

-- =============================================
-- 9. SEED DATA: Categories & Game Types
-- =============================================

-- Insert Categories
INSERT INTO game_categories (name, description, icon_name, gradient_colors, sort_order, is_adult) VALUES
    ('Discovery', 'New explorations and late-night vibes', 'Compass', ARRAY['#7C4DFF', '#651FFF'], 1, false),
    ('As a Couple', 'Strengthening your bond and shared history', 'Heart', ARRAY['#FF4081', '#F50057'], 2, false),
    ('Date Night', 'Pure entertainment and engaging choices', 'Star', ARRAY['#FF6D00', '#FF9100'], 3, false),
    ('Little Spice', 'Bold, unfiltered intimacy (18+)', 'Flame', ARRAY['#D50000', '#FF1744'], 4, true);

-- Insert Game Types
-- Discovery
INSERT INTO game_types (category_id, name, slug, description, icon_name, gradient_colors, gameplay_type, sort_order, is_adult, has_virtual_mode, has_spice_meter) VALUES
    ((SELECT id FROM game_categories WHERE name = 'Discovery'), 'Crush', 'crush', 'Flirty content in the sweet spot between romance and deep conversation', 'Heart', ARRAY['#EC407A', '#D81B60'], 'prompt', 1, false, false, false),
    ((SELECT id FROM game_categories WHERE name = 'Discovery'), 'Deep Night', 'deep-night', 'Late-night confessions and vulnerable, soulful sharing', 'Moon', ARRAY['#5C6BC0', '#3949AB'], 'prompt', 2, false, false, false),
    ((SELECT id FROM game_categories WHERE name = 'Discovery'), 'Is it Okay?', 'is-it-okay', 'A judgement-free zone for controversial relationship questions', 'HelpCircle', ARRAY['#26A69A', '#00897B'], 'debate', 3, false, false, false);

-- As a Couple
INSERT INTO game_types (category_id, name, slug, description, icon_name, gradient_colors, gameplay_type, sort_order, is_adult, has_virtual_mode, has_spice_meter) VALUES
    ((SELECT id FROM game_categories WHERE name = 'As a Couple'), 'Connected', 'connected', 'Meaningful dialogue focused on strengthening emotional foundations', 'Link', ARRAY['#42A5F5', '#1E88E5'], 'prompt', 1, false, false, false),
    ((SELECT id FROM game_categories WHERE name = 'As a Couple'), 'Who''s More Likely', 'whos-more-likely', 'A fun, superlative-style game to compare perceptions', 'Users', ARRAY['#AB47BC', '#8E24AA'], 'vote', 2, false, false, false),
    ((SELECT id FROM game_categories WHERE name = 'As a Couple'), 'Memory Lane', 'memory-lane', 'A nostalgic journey through your relationship milestones', 'Camera', ARRAY['#66BB6A', '#43A047'], 'prompt', 3, false, false, false),
    ((SELECT id FROM game_categories WHERE name = 'As a Couple'), 'Mirror', 'mirror', 'How well do you know your partner? Test your knowledge!', 'Eye', ARRAY['#29B6F6', '#039BE5'], 'quiz', 4, false, false, false);

-- Date Night
INSERT INTO game_types (category_id, name, slug, description, icon_name, gradient_colors, gameplay_type, sort_order, is_adult, has_virtual_mode, has_spice_meter) VALUES
    ((SELECT id FROM game_categories WHERE name = 'Date Night'), 'Tell Me Everything', 'tell-me-everything', 'Total transparency prompts for honest storytelling', 'MessageCircle', ARRAY['#FFCA28', '#FFB300'], 'prompt', 1, false, false, false),
    ((SELECT id FROM game_categories WHERE name = 'Date Night'), 'Between Us', 'between-us', 'A wildcard mix of funny anecdotes and serious reflections', 'Shuffle', ARRAY['#26C6DA', '#00ACC1'], 'wildcard', 2, false, false, false),
    ((SELECT id FROM game_categories WHERE name = 'Date Night'), 'Would You Rather', 'would-you-rather', 'Classic dilemma-based choices tailored for couples', 'ArrowLeftRight', ARRAY['#FFA726', '#FB8C00'], 'choice', 3, false, false, false);

-- Little Spice (18+)
INSERT INTO game_types (category_id, name, slug, description, icon_name, gradient_colors, gameplay_type, sort_order, is_adult, has_virtual_mode, has_spice_meter) VALUES
    ((SELECT id FROM game_categories WHERE name = 'Little Spice'), 'Would You Rather Hot', 'would-you-rather-hot', 'Uncensored, intimacy-based dilemmas. No filters.', 'Flame', ARRAY['#E53935', '#C62828'], 'choice', 1, true, true, true),
    ((SELECT id FROM game_categories WHERE name = 'Little Spice'), 'Intimacy', 'intimacy', 'Prompts designed to build physical and emotional heat', 'Sparkles', ARRAY['#AD1457', '#880E4F'], 'prompt', 2, true, true, true),
    ((SELECT id FROM game_categories WHERE name = 'Little Spice'), 'Hard-Dare', 'hard-dare', 'Challenging actions for couples ready to push boundaries', 'Zap', ARRAY['#6A1B9A', '#4A148C'], 'dare', 3, true, true, true);
